"""application.compiler.migrations — 加载前 IR 与 manifest 一致性校验.

``validate_against_manifests(ir_dict) -> list[str]``：在 ``CanvasPage.from_workflow_dict``
之前调用，列出 manifest / IR 之间的偏移：

- 节点 ``schema_id`` 不在 ``RegistryHub.nodes``（will be loaded as placeholder）
- 节点 ``params`` 中存在 manifest 未声明的 key（漂移；IR 加载会丢弃这些值）
- 边引用的 ``source_port`` / ``target_port`` 在对应 manifest 的 inputs/outputs 中找不到
- 节点 ``schema_id`` 缺失或 ``id`` 缺失（结构性损坏）

返回 ``list[str]`` 警告条目（不抛异常 / 不阻塞加载）；调用方（MainWindow）按
``log_warning`` 把每条吐到 CmdLogWidget，让用户察觉哪些节点变 placeholder
或哪些边将丢失数据。

校验只读取 ``registers.nodes`` —— 与 ``RegistryHub.load_all`` 的 ir / brands /
robots 等域无关，所以可以在 ``RegistryHub`` 加载后任意时刻调用。
"""
from __future__ import annotations

from typing import Any, Dict, List


def validate_against_manifests(ir_dict: Dict[str, Any]) -> List[str]:
    """对 IR-shape canvas dict 做 manifest 一致性校验，返回告警字符串列表."""
    warnings: List[str] = []
    if not isinstance(ir_dict, dict):
        warnings.append("IR root is not a dict")
        return warnings

    # 延迟 import：避免 application.compiler 在 RegistryHub 之前加载
    try:
        from registers import nodes as nodes_registry
    except Exception as exc:
        warnings.append(f"registers.nodes import failed: {exc!r}")
        return warnings

    nodes = ir_dict.get("nodes") or []
    edges = ir_dict.get("edges") or []
    if not isinstance(nodes, list):
        warnings.append("IR 'nodes' is not a list")
        nodes = []
    if not isinstance(edges, list):
        warnings.append("IR 'edges' is not a list")
        edges = []

    # Per-instance: schema_id (used in messages) + the full set of legal
    # port names — manifest static inputs/outputs PLUS any dynamic ports
    # the node generates from its own params (currently only
    # training_motion does this, via ``iter_reward_port_specs``).
    node_schema: Dict[str, str] = {}
    node_port_names: Dict[str, set] = {}
    for n in nodes:
        if not isinstance(n, dict):
            warnings.append(f"node entry is not a dict: {n!r}")
            continue
        inst_id = n.get("id")
        schema_id = n.get("schema_id")
        if not inst_id:
            warnings.append(f"node missing 'id': schema_id={schema_id!r}")
            continue
        if not schema_id:
            warnings.append(f"node missing 'schema_id': id={inst_id!r}")
            continue
        node_schema[inst_id] = schema_id

        manifest = nodes_registry.get_manifest(schema_id)
        if manifest is None:
            warnings.append(
                f"node {inst_id!r} schema_id {schema_id!r} 未在 registry 注册 → "
                f"将以 placeholder 渲染（数据保留，无法编辑）"
            )
            continue

        # 参数 key 漂移：manifest 没声明但 IR 携带的 key（save 时会丢弃）
        spec_keys = {p.key for p in manifest.parameters}
        params = n.get("params") or {}
        if isinstance(params, dict):
            extra = [k for k in params.keys() if k not in spec_keys and k != "backend"]
            if extra:
                warnings.append(
                    f"node {inst_id!r} ({schema_id}) 携带 manifest 未声明的参数 key: {extra} → "
                    f"加载后会被忽略"
                )

        # Full legal port name set = static manifest + dynamic ports
        # generated by the node from its own params.
        port_names = {p.name for p in manifest.inputs} | {p.name for p in manifest.outputs}
        port_names |= _dynamic_port_names(schema_id, params if isinstance(params, dict) else {})
        node_port_names[inst_id] = port_names

    # Edge 端口校验
    for e in edges:
        if not isinstance(e, dict):
            warnings.append(f"edge entry is not a dict: {e!r}")
            continue
        eid = e.get("id") or "<unknown>"
        src_id = e.get("source_node")
        dst_id = e.get("target_node")
        src_p = e.get("source_port")
        dst_p = e.get("target_port")
        for label, nid in (("source", src_id), ("target", dst_id)):
            if not nid:
                warnings.append(f"edge {eid} {label}_node 缺失")
                continue
            if nid not in node_schema:
                warnings.append(f"edge {eid} {label}_node {nid!r} 在节点列表中找不到")
        if src_id in node_port_names and src_p:
            if src_p not in node_port_names[src_id]:
                warnings.append(
                    f"edge {eid} source_port {src_p!r} 在 manifest "
                    f"{node_schema[src_id]} 的 inputs/outputs 中找不到"
                )
        if dst_id in node_port_names and dst_p:
            if dst_p not in node_port_names[dst_id]:
                warnings.append(
                    f"edge {eid} target_port {dst_p!r} 在 manifest "
                    f"{node_schema[dst_id]} 的 inputs/outputs 中找不到"
                )

    return warnings


def _dynamic_port_names(schema_id: str, params_raw: Dict[str, Any]) -> set:
    """Return the input port names a node generates dynamically from its
    own params (NOT declared in the static manifest). Currently only
    ``training_motion`` produces these — one ``reward_in__<item_id>``
    port per enabled entry in its ``training_items`` dict.

    ``params_raw`` is the IR-shape param dict (each value is
    ``{name, value, param_type}``); we unwrap to raw values before
    invoking the node-side enumerator so it sees the same shape it
    would inside the running canvas.
    """
    if schema_id != "training_motion":
        return set()
    try:
        from nodes.training_motion.node import iter_reward_port_specs
    except Exception:
        return set()
    params_unwrapped = {
        k: (v.get("value") if isinstance(v, dict) and "value" in v else v)
        for k, v in params_raw.items()
    }
    return {p.name for p in iter_reward_port_specs(params_unwrapped)}


__all__ = ["validate_against_manifests"]
