"""Isaac Lab preset — Go2 Rough Velocity."""

from __future__ import annotations


NAME = 'Go2 Rough Velocity'
TASK_NAME = 'Isaac-Velocity-Rough-Unitree-Go2-v0'
ORDER = 1
ENTRY = {   'play_ground_setting': {   'sim_dt': '0.005',
                               'gravity_z': '-9.81',
                               'gpu_max_rigid_contact_count': '524288',
                               'gpu_max_rigid_patch_count': '327680'},
    'il_actuator_config': {   'joint_names_expr': '.*',
                              'model': 'implicit_pd',
                              'stiffness': '25.0',
                              'damping': '0.5',
                              'effort_limit': '23.5',
                              'velocity_limit': '30.0'},
    'il_observation': {   'obs_terms': '{"base_lin_vel": 1.0, "base_ang_vel": 1.0, "projected_gravity": 1.0, '
                                       '"velocity_command": 1.0, "joint_pos": 1.0, "joint_vel": 1.0, "last_action": '
                                       '1.0, "height_scan": 1.0}',
                          'group_name': 'policy',
                          'enable_corruption': 'true',
                          'corruption_noise_std': '0.05'},
    'rewards': {   'backend': 'isaac_lab',
                   'reward_terms': '{"track_lin_vel_xy": 1.5, "track_ang_vel_z": 0.75, "lin_vel_z_penalty": -2.0, '
                                   '"ang_vel_xy_penalty": -0.05, "joint_torque_penalty": -0.0002, '
                                   '"joint_accel_penalty": -2.5e-07, "action_rate_penalty": -0.01, "feet_air_time": '
                                   '0.01, "flat_orientation": 0.0}',
                   'std': '0.25',
                   'threshold': '0.5'},
    'terminations': {'backend': 'isaac_lab', 'termination_conditions': '{"time_out": 20.0, "illegal_contact": 1.0}'},
    'domain_rand': {   'backend': 'isaac_lab',
                       'enable_friction_rand': 'true',
                       'friction_mode': 'startup',
                       'static_friction_range': '[0.5, 1.5]',
                       'dynamic_friction_range': '[0.4, 1.2]',
                       'restitution_range': '[0.0, 0.2]',
                       'enable_mass_rand': 'true',
                       'mass_mode': 'startup',
                       'mass_target_body': 'base',
                       'mass_offset_range': '[-1.0, 3.0]',
                       'enable_external_push': 'false',
                       'push_mode': 'interval',
                       'push_interval_range_s': '[10.0, 15.0]',
                       'push_velocity_x_range': '[-0.5, 0.5]',
                       'push_velocity_y_range': '[-0.5, 0.5]',
                       'enable_init_pose_rand': 'true',
                       'init_pose_mode': 'reset',
                       'init_pos_x_range': '[-0.5, 0.5]',
                       'init_pos_y_range': '[-0.5, 0.5]',
                       'init_yaw_range': '[-3.14, 3.14]',
                       'enable_joint_noise': 'true',
                       'joint_noise_mode': 'reset',
                       'joint_pos_noise': '0.0',
                       'joint_vel_noise': '0.0'},
    'il_policy_network': {   'actor_hidden_dims': '[128, 64, 32]',
                             'critic_hidden_dims': '[128, 64, 32]',
                             'activation': 'elu',
                             'init_noise_std': '-1.0',
                             'disc_hidden_dims': '[1024, 512]'},
    'il_ppo_trainer': {   'training_mode': 'PPO',
                          'max_iterations': '1500',
                          'num_steps_per_env': '24',
                          'num_learning_epochs': '5',
                          'num_minibatches': '4',
                          'learning_rate': '0.001',
                          'discount_factor': '0.99',
                          'gae_lambda': '0.95',
                          'clip_param': '0.2',
                          'entropy_coef': '0.01',
                          'value_loss_coef': '1.0',
                          'max_grad_norm': '1.0',
                          'schedule': 'adaptive',
                          'desired_kl': '0.01',
                          'save_interval': '100',
                          'seed': '42'},
    'export': {'export_onnx': 'true', 'export_torchscript': 'false', 'bundle_name': '', 'auto_import': 'true'},
    '_meta': {'task_name': 'Isaac-Velocity-Rough-Unitree-Go2-v0'}}
