# SPDX-FileCopyrightText: 2026 SU CHANG
# SPDX-License-Identifier: Apache-2.0

"""BASING ON ULTIMA_SDK
"""

# ---- logger -----------------------------------------------------------
from .logger import (
    LogSignal,
    LoguruHandler,
    install_loguru_bridge,
    set_debug_flag,
    get_debug_flag,
    set_info_flag,
    get_info_flag,
    log,
    log_info,
    log_success,
    log_warning,
    log_error,
    log_debug,
)

# ---- sys --------------------------------------------------------------
from .sys import (
    # 基础设施
    Paths,
    Config,
    CrashHook,
    install_crash_hook,
    uninstall_crash_hook,
    # Config 模块级便捷别名
    get_value,
    set_value,
    get_color,
    get_font_size,
    # 通用文件 I/O
    DataManager,
    load_data,
    read_data,
    up_data,
    save_data,
    get_data_value,
    # 通用数据推送（local FS + cloud channel via Storage.register_cloud_transport）
    Storage,
    push_data,
    # 资源查找
    Assets,
    # i18n
    I18n,
    tr,
    # 任务系统
    Task,
    TaskCancelledException,
    TaskStatus,
    TaskSignal,
    TaskWorker,
    TaskSlot,
    TasksManager,
    get_tasks_manager,
    get_task_signal,
    set_max_slots,
    # 全局文件脏状态广播
    DirtyTracker,
    getDirtyTracker,
    setDirtyBaseline,
    reportDirtyText,
    markDirtyClean,
    clearDirtyTracker,
    isDirty,
)

# ---- ui ---------------------------------------------------------------
from .ui import (
    TyperThread,
    SwitchButton,
    CmdLogWidget,
    I18nLabel,
    I18nButton,
    i18n_bind,
    LaviButton,
    setButton,
    LaviLabel,
    setText,
    LaviProgressBar,
    SettingConfirm,
    LaviComboBox,
    setComboBox,
    TitleGroupBox,
    setTitleGroupBox,
    WheelSelector,
    setWheelSelector,
    SliderSwitch,
    setSliderSwitch,
    TagInput,
    setTagInput,
    CheckboxItem,
    setCheckboxItem,
    LaviTabTable,
    setLaviTabTable,
)

# ---- canvas widget 库（项目特化的 paint helper + NodeBuilder 糖 + themed inputs + Node_* 家族）----
from .canvas import (
    PORT_HIT_R,
    PORT_R,
    PORT_TYPE_COLORS,
    LaviCodeEditor,
    LaviDoubleSpinBox,
    LaviLineEdit,
    LaviSpinBox,
    NodeBuilder,
    # Node_* — badges
    Node_ClipRefIndicator,
    Node_ModulePolarityBadge,
    # Node_* — port item
    Node_TrainingNodePort,
    # Node_* — pickers
    Node_RichChoiceCard,
    Node_RichChoicePopup,
    Node_RichChoicePicker,
    Node_TaskTypePicker,
    Node_ObsComponentsPicker,
    Node_DropdownChoicePicker,
    Node_SceneTypePicker,
    Node_ExportBundlePicker,
    Node_StartPointChoicePicker,
    Node_MotionLibraryPicker,
    Node_MainPicker,
    # Node_* — sliders
    Node_RangeHandleSlider,
    Node_DualHandleRangeSlider,
    Node_NodeSlider,
    Node_ModuleCurveSlider,
    Node_CurvePreviewArea,
    # Node_* — inputs
    Node_IndexButton,
    Node_NodeInputer,
    Node_CodeEdit,
    Node_ModuleValueButton,
    # Node_* — popups（frameless 就地编辑）
    Node_AnchoredPopup,
    Node_DataInput,
    Node_CodeEditorPopup,
    Node_EditorPopupHost,
    # Node_* — rows
    Node_NodeRow,
    Node_PortInputRow,
    Node_ConditionSet,
    Node_OutputSet,
    Node_InputSetting,
    Node_ComboSetting,
    Node_BehaviorSetting,
    Node_ScriptSetting,
    Node_ScriptInAndOut,
    Node_NodeTableRowsWidget,
    Node_RegistryModuleRow,
    # Node_* — composites
    Node_SaveListButton,
    Node_BufferSizePickerWidget,
    Node_MotionFilePickerWidget,
    Node_FPSSliderWidget,
    Node_PreviewButtonWidget,
    Node_AMPResultsPanel,
    Node_TrainingItemRow,
    Node_TrainingItemEditor,
    Node_RegistryModuleEditor,
    # Node_* — dialogs
    Node_StageOverrideDialog,
    Node_StageSwitchCriteriaDialog,
    Node_StageSwitchEditorWidget,
    RangeSliderHitTest,
    default_color_hex,
    draw_choice_dropdown,
    draw_dot_port,
    draw_edit_button,
    draw_polarity_badge,
    draw_range_slider,
    get_port_color,
    known_types,
    make_port_visual,
    setCodeEditor,
    setDoubleSpinBox,
    setLineEdit,
    setSpinBox,
)

# ---- compiler — code editor widget primitives ------------------------
from .compiler import (
    CodeEditorWidget,
    CodeEditorDialog,
    PythonSyntaxHighlighter,
    JsonSyntaxHighlighter,
)

# 兼容别名：`from ULTIMA_SDK import config` 仍可用作 Config
config = Config

# 导入 SDK 时初始化 i18n（读 sdk.ini 的 [Localisation].lang，加载默认语种 + EN base）
I18n.init()


__version__ = "1.1.0"

__all__ = [
    # logger
    "LogSignal",
    "LoguruHandler",
    "install_loguru_bridge",
    "set_debug_flag",
    "get_debug_flag",
    "set_info_flag",
    "get_info_flag",
    "log",
    "log_info",
    "log_success",
    "log_warning",
    "log_error",
    "log_debug",
    # sys (infra)
    "Paths",
    "Config",
    "config",
    "CrashHook",
    "install_crash_hook",
    "uninstall_crash_hook",
    # sys (Config aliases)
    "get_value",
    "set_value",
    "get_color",
    "get_font_size",
    # sys (data I/O)
    "DataManager",
    "load_data",
    "read_data",
    "up_data",
    "save_data",
    "get_data_value",
    # sys (data push)
    "Storage",
    "push_data",
    # sys (assets)
    "Assets",
    # sys (i18n)
    "I18n",
    "tr",
    # sys (tasks)
    "Task",
    "TaskCancelledException",
    "TaskStatus",
    "TaskSignal",
    "TaskWorker",
    "TaskSlot",
    "TasksManager",
    "get_tasks_manager",
    "get_task_signal",
    "set_max_slots",
    # sys (dirty)
    "DirtyTracker",
    "getDirtyTracker",
    "setDirtyBaseline",
    "reportDirtyText",
    "markDirtyClean",
    "clearDirtyTracker",
    "isDirty",
    # ui
    "TyperThread",
    "SwitchButton",
    "CmdLogWidget",
    "I18nLabel",
    "I18nButton",
    "i18n_bind",
    "LaviButton",
    "setButton",
    "LaviLabel",
    "setText",
    "LaviProgressBar",
    "SettingConfirm",
    "LaviComboBox",
    "setComboBox",
    "TitleGroupBox",
    "setTitleGroupBox",
    "WheelSelector",
    "setWheelSelector",
    "SliderSwitch",
    "setSliderSwitch",
    "TagInput",
    "setTagInput",
    "CheckboxItem",
    "setCheckboxItem",
    "LaviTabTable",
    "setLaviTabTable",
    # canvas (paint helpers + NodeBuilder + themed inputs)
    "PORT_TYPE_COLORS",
    "PORT_R",
    "PORT_HIT_R",
    "NodeBuilder",
    "RangeSliderHitTest",
    "default_color_hex",
    "draw_choice_dropdown",
    "draw_dot_port",
    "draw_edit_button",
    "draw_polarity_badge",
    "draw_range_slider",
    "get_port_color",
    "known_types",
    "make_port_visual",
    "LaviCodeEditor",
    "LaviDoubleSpinBox",
    "LaviLineEdit",
    "LaviSpinBox",
    "setCodeEditor",
    "setDoubleSpinBox",
    "setLineEdit",
    "setSpinBox",
    # compiler — code editor primitives
    "CodeEditorWidget",
    "CodeEditorDialog",
    "PythonSyntaxHighlighter",
    "JsonSyntaxHighlighter",
    # canvas Node_* — pickers
    "Node_RichChoiceCard",
    "Node_RichChoicePopup",
    "Node_RichChoicePicker",
    "Node_TaskTypePicker",
    "Node_ObsComponentsPicker",
    "Node_DropdownChoicePicker",
    "Node_SceneTypePicker",
    "Node_ExportBundlePicker",
    "Node_StartPointChoicePicker",
    "Node_MotionLibraryPicker",
    "Node_MainPicker",
    # canvas Node_* — sliders
    "Node_RangeHandleSlider",
    "Node_DualHandleRangeSlider",
    "Node_NodeSlider",
    "Node_ModuleCurveSlider",
    "Node_CurvePreviewArea",
    # canvas Node_* — inputs
    "Node_IndexButton",
    "Node_NodeInputer",
    "Node_CodeEdit",
    "Node_ModuleValueButton",
    # canvas Node_* — popups（frameless 就地编辑）
    "Node_AnchoredPopup",
    "Node_DataInput",
    "Node_CodeEditorPopup",
    "Node_EditorPopupHost",
    # canvas Node_* — rows
    "Node_NodeRow",
    "Node_PortInputRow",
    "Node_ConditionSet",
    "Node_OutputSet",
    "Node_InputSetting",
    "Node_ComboSetting",
    "Node_BehaviorSetting",
    "Node_ScriptSetting",
    "Node_ScriptInAndOut",
    "Node_NodeTableRowsWidget",
    "Node_RegistryModuleRow",
    # canvas Node_* — badges
    "Node_ModulePolarityBadge",
    "Node_ClipRefIndicator",
    # canvas Node_* — port item
    "Node_TrainingNodePort",
    # canvas Node_* — composites
    "Node_SaveListButton",
    "Node_BufferSizePickerWidget",
    "Node_MotionFilePickerWidget",
    "Node_FPSSliderWidget",
    "Node_PreviewButtonWidget",
    "Node_AMPResultsPanel",
    "Node_TrainingItemRow",
    "Node_TrainingItemEditor",
    "Node_RegistryModuleEditor",
    # canvas Node_* — dialogs
    "Node_StageOverrideDialog",
    "Node_StageSwitchCriteriaDialog",
    "Node_StageSwitchEditorWidget",
]
